export const MOKUROKU_INDEX_LIST_BEGINNING_TEXT = '%% Mokuroku: Beginning of the autogenerated index file list  %%';
export const MOKUROKU_INDEX_LIST_END_TEXT = '%% Mokuroku: End of the autogenerated index file list  %%';
